insert into person (
person_id,                        -- person_id is autogenerated with a sequence
gender_concept_id,
year_of_birth,
month_of_birth,
day_of_birth,
birth_datetime,
race_concept_id,
ethnicity_concept_id,
location_id,
provider_id,
care_site_id,
person_source_value,
gender_source_value,
gender_source_concept_id,
race_source_value,
race_source_concept_id,
ethnicity_source_value,
ethnicity_source_concept_id
)
select
nextval('person_person_id_seq'), -- person_id
case upper(p.gender)
when 'M' then 8507
when 'F' then 8532
         else 0
end,                             -- gender_concept_id
extract(year  from p.birthdate),       -- year_of_birth
extract(month from p.birthdate),       -- month_of_birth
extract(day   from p.birthdate),       -- day_of_birth
p.birthdate,                           -- birth_datetime
-- dod,                          -- useful for the death table, not here
case upper(p.race)               -- race_concept_id
when 'WHITE' then 8527
when 'BLACK' then 8516
when 'ASIAN' then 8515
else 0
end,
case when upper(p.ethnicity) in
('CENTRAL_AMERICAN',
 'DOMINICAN',
 'MEXICAN',
 'PUERTO_RICAN',
 'SOUTH_AMERICAN')
then 38003563 else 0 end,        -- ethnicity_concept_id
0,															 -- location_id
NULL,                            -- provider_id
NULL,                            -- care_site_id
id,                              -- person_source_value - stores native id
p.gender,                        -- gender_source_value - stores native gender
0,                               -- gender_source_concept_id
p.race,                          -- race_source_value - stores native race
0,                               -- race_source_concept_id
p.ethnicity,                     -- ethnicity_source_value - stores native ethnicity
0                                -- ethnicity_source_concept_id
from patients p;
