copy allergies      from 'D:\Apps\Git\synthea\ETL\CSV\synthea_data\allergies.csv'      with (FORMAT CSV, DELIMITER E',', HEADER true, NULL '');
copy careplans      from 'D:\Apps\Git\synthea\ETL\CSV\synthea_data\careplans.csv'      with (FORMAT CSV, DELIMITER E',', HEADER true, NULL '');
copy conditions     from 'D:\Apps\Git\synthea\ETL\CSV\synthea_data\conditions.csv'     with (FORMAT CSV, DELIMITER E',', HEADER true, NULL '');
copy encounters     from 'D:\Apps\Git\synthea\ETL\CSV\synthea_data\encounters.csv'     with (FORMAT CSV, DELIMITER E',', HEADER true, NULL '');
copy immunizations  from 'D:\Apps\Git\synthea\ETL\CSV\synthea_data\immunizations.csv'  with (FORMAT CSV, DELIMITER E',', HEADER true, NULL '');
copy medications    from 'D:\Apps\Git\synthea\ETL\CSV\synthea_data\medications.csv'    with (FORMAT CSV, DELIMITER E',', HEADER true, NULL '');
copy observations   from 'D:\Apps\Git\synthea\ETL\CSV\synthea_data\observations.csv'   with (FORMAT CSV, DELIMITER E',', HEADER true, NULL '');
copy patients       from 'D:\Apps\Git\synthea\ETL\CSV\synthea_data\patients.csv'       with (FORMAT CSV, DELIMITER E',', HEADER true, NULL '');
copy procedures     from 'D:\Apps\Git\synthea\ETL\CSV\synthea_data\procedures.csv'     with (FORMAT CSV, DELIMITER E',', HEADER true, NULL '');
